if: tag IS present

language: minimal

before_install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_extended_0.74.3_Linux-64bit.deb
  - sudo dpkg -i hugo_extended_0.74.3_Linux-64bit.deb

env:
  - HUGO_ENV=production

script: hugo --buildFuture --destination production

deploy:
  - provider: pages
    edge: true
    fqdn: www.willamettevalleybandb.com
    github_token: $GITHUB_TOKEN
    target_branch: gh-pages
    local_dir: production
    on:
      tags: true
