baseURL = "https://willamettevalleybandb.com/"
languageCode = "en-us"
title = "Willamette Valley Bed and Breakfast - Newberg, Oregon"

Paginate = 3
enableRobotsTXT = true

[params]
  default_featured_image = "/img/bg-masthead.md"

  recent_events_per_month = 10
  recent_events_months = ["September", "June"]

  background_color_class = "bg-black"

[menu]
  [[menu.about]]
    name = "About"
    url = "#about"

  [[menu.about]]
    name = "Location"
    url = "#location"

  [[menu.about]]
    name = "Reserve Now"
    url = "/#reserve"

  [[menu.index]]
    name = "About"
    url = "#about"
    weight = 1

  [[menu.index]]
    name = "Reserve"
    url = "#reserve"
    weight = 2

  [[menu.index]]
    name = "Information"
    url = "#info"
    weight = 3

  [[menu.index]]
    name = "News"
    url = "#news"
    weight = 4

  [[menu.index]]
    name = "Contact Us"
    url = "#contact"
    weight = 5

  [[menu.page]]
    name = "About"
    url = "/about"

  [[menu.page]]
    name = "Reserve Now"
    url = "/#reserve"

  [[menu.post]]
    name = "All Posts"
    url = "/posts"

  [[menu.post]]
    name = "Reserve Now"
    url = "/#reserve"

  [[menu.event]]
    name = "All Events"
    url = "/events"

  [[menu.event]]
    name = "Reserve Now"
    url = "/#reserve"
