baseURL = "https://test.willamettevalleybandb.com/"
languageCode = "en-us"
title = "Willamette Valley Bed and Breakfast - Newberg, Oregon"

Paginate = 3
enableRobotsTXT = true

[params]
  default_featured_image = "/img/bg-masthead.md"

  recent_events_per_month = 10
  recent_events_months = ["September", "June"]

  background_color_class = "bg-black"
