baseURL = "https://test.willamettevalleybandb.com/"
languageCode = "en-us"
title = "Willamette Valley Bed and Breakfast - Newberg, Oregon"

Paginate = 3
enableRobotsTXT = true
[params]
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 3
