backend:
  name: github
  repo: kdef/wvbnb
  branch: master
media_folder: "static/img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog Posts" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    # this excludes the file contents/posts/_index.md because it has a field "description"
    # see this issue: https://github.com/netlify/netlify-cms/issues/1000
    filter: {field: "description"}
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "featured_image", widget: "image"}
      - {label: "Featured Image Alt Text", name: "featured_image_alt_text", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "events"
    label: "Events"
    folder: "content/events"
    create: true
    # see this issue: https://github.com/netlify/netlify-cms/issues/1000
    filter: {field: "description"}
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Event Date", name: "date", widget: "datetime"}
      - {label: "Link", name: "external_link", widget: "string", required: false}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Featured Image Alt Text", name: "featured_image_alt_text", widget: "string", required: false}
      - {label: "Description", name: "body", widget: "markdown"}
  - name: "pages"
    label: "All Pages"
    files:
      - file: "content/_index.md"
        name: "index"
        label: "Home"
        fields:
          - {label: "Slogan", name: "slogan", widget: "string"}
          - {label: "Featured Image", name: "featured_image", widget: "image"}
          - {label: "Featured Image Alt Text", name: "featured_image_alt_text", widget: "string"}
          - {label: "About Title", name: "about_title", widget: "string"}
          - {label: "About Text", name: "about_text", widget: "text"}
          - {label: "About Image", name: "about_image", widget: "image"}
          - {label: "Reserve Text", name: "reserve_text", widget: "text"}
          - {label: "Regional Image", name: "regional_image", widget: "image"}
          - {label: "Regional Title", name: "regional_title", widget: "string"}
          - {label: "Regional Text", name: "regional_text", widget: "text"}
          - {label: "Suites Image", name: "suites_image", widget: "image"}
          - {label: "Suites Title", name: "suites_title", widget: "string"}
          - {label: "Suites Text", name: "suites_text", widget: "text"}
          - {label: "Breakfast Image", name: "breakfast_image", widget: "image"}
          - {label: "Breakfast Title", name: "breakfast_title", widget: "string"}
          - {label: "Breakfast Text", name: "breakfast_text", widget: "text"}
          - {label: "News Text", name: "news_text", widget: "markdown"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/about/_index.md"
        name: "about"
        label: "About"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Featured Image", name: "featured_image", widget: "image"}
          - {label: "Featured Image Alt Text", name: "featured_image_alt_text", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/posts/_index.md"
        name: "posts"
        label: "Blog"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Featured Image", name: "featured_image", widget: "image"}
          - {label: "Featured Image Alt Text", name: "featured_image_alt_text", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/events/_index.md"
        name: "events"
        label: "Events"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Featured Image", name: "featured_image", widget: "image"}
          - {label: "Featured Image Alt Text", name: "featured_image_alt_text", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
